name: UHC
api-version: 1.20
main: ru.main.UHCPlugin
version: 3.0
commands:
 test:
  description: Debug command
  usage: /test
 gm:
  description: Fast gamemode switch
  usage: /gm [0-3]
 start:
  description: Start game
  usage: /start
 end:
  description: End game
  usage: /end
 lobby:
  description: Вернуться в лобби
  usage: /lobby
 arena:
  description: Просмотр арены
  usage: /arena <название_арены>
 skip:
  description: Skip the current GameState
  usage: /skip
 map:
  description: Actions with map
  usage: /map <regen/create/remove/status>
 rating:
  description: Посмотреть рейтинг
  usage: /rating
 drop:
  description: Drops debug
  usage: /drop <air/cave> <reset/drop/changeloc>
 customitem:
  description: CustomItem debug
  usage: /customitem
 timer:
  description: Controls ingame timer
  usage: /timer <reset/set/add> [value]
 mutator:
  description: Shows active mutators (use only in game)
  usage: /mutator
 optmutator:
  description: Mutator debug
  usage: /optmutator <activate/deactivate/clear/new> [name]
 inv:
  description: Показать инвентарь игрока; работает только с мутатором Всевидящий
  usage: /inv <ник>
 class:
  description: Установить класс (в лобби), или показать информацию о выбранном классе (в игре)
  usage: /class
 teammate:
  description: Формирование команды для игры в режиме дуо
  usage: /teammate <request/accept/decline/leave> [player]
 worldtime:
  description: Set the time in the current world
  usage: /worldtime <day/night/noon/midnight/[number]>
  aliases: [wt]
 editarena:
  description: Read or write an arena option
  usage: /editarena <arena> <option> [value]
  aliases: [ea]
 requests:
  description: Открыть меню запросов
  usage: /requests
 artifacts:
  description: Открыть меню артефактов
  usage: /artifacts